SCENARIO_NAME = "baseline"

WIDTH = 20
HEIGHT = 20

POPULATION = 1000
INITIAL_INFECTED = 3
CHILD_RATE = 0.25
SENIOR_RATE = 0.15
HOUSEHOLD_SIZE = 4

CHILD_MORTALITY_RATE = 0.001
CHILD_MOBILITY = 1.0
ADULT_MORTALITY_RATE = 0.005
SENIOR_MORTALITY_RATE = 0.03
SENIOR_MOBILITY = 0.4

LOCKDOWN = False
LOCKDOWN_MOBILITY = 0.2
MASKS_ENABLED = False
MASK_TRANSMISSION_REDUCTION = 0.4
MASK_COMPLIANCE = 0.7
QUARANTINE_ENABLED = True
QUARANTINE_COMPLIANCE = 0.9
SCHOOL_CLOSED = False
WORK_CLOSED = False

TESTING_RATE = 0.5
DETECTED_TRANSMISSION_MULTIPLIER = 0.3

ASYMPTOMATIC_RATE = 0.3
ASYMPTOMATIC_TRANSMISSION_MULTIPLIER = 0.6
HOUSEHOLD_TRANSMISSION_MULTIPLIER = 1.5

ISOLATION_RATE = 0.8

INFECTION_PROBABILITY = 0.4
RECOVERY_TIME = 5
INCUBATION_TIME = 2

VACCINATION_RATE = 0.2
VACCINE_EFFECTIVENESS = 0.9

SIMULATION_STEPS = 500

RANDOM_SEED = 42