SCENARIO_NAME = "Realistic seasonal flu wave 5000 population"

WIDTH = 90
HEIGHT = 90

SIMULATION_STEPS = 3000

POPULATION = 5000
INITIAL_INFECTED = 18

INFECTION_PROBABILITY = 0.00072

INCUBATION_TIME = 40
RECOVERY_TIME = 90

ASYMPTOMATIC_RATE = 0.30
ASYMPTOMATIC_TRANSMISSION_MULTIPLIER = 0.35

CHILD_RATE = 0.20
SENIOR_RATE = 0.20

CHILD_MORTALITY_RATE = 0.0001
ADULT_MORTALITY_RATE = 0.0010
SENIOR_MORTALITY_RATE = 0.060

VACCINATION_RATE = 0.38
VACCINE_EFFECTIVENESS = 0.55

HOUSEHOLD_SIZE = 3
HOUSEHOLD_TRANSMISSION_MULTIPLIER = 1.35

ISOLATION_RATE = 0.25

MASKS_ENABLED = True
MASK_COMPLIANCE = 0.15
MASK_TRANSMISSION_REDUCTION = 0.35

QUARANTINE_ENABLED = True
QUARANTINE_COMPLIANCE = 0.30

TESTING_RATE = 0.15
DETECTED_TRANSMISSION_MULTIPLIER = 0.60

LOCKDOWN = False
AUTO_LOCKDOWN = False
LOCKDOWN_THRESHOLD = 450
AUTO_LOCKDOWN_RELEASE = False
LOCKDOWN_RELEASE_THRESHOLD = 120
LOCKDOWN_MOBILITY = 0.45

WORK_CLOSED = False
AUTO_WORK_CLOSURE = False
WORK_CLOSURE_THRESHOLD = 450
AUTO_WORK_REOPEN = False
WORK_REOPEN_THRESHOLD = 120

AUTO_SCHOOL_CLOSURE = True
SCHOOL_CLOSURE_THRESHOLD = 110
AUTO_SCHOOL_REOPEN = True
SCHOOL_REOPEN_THRESHOLD = 10

AUTO_MASK_COMPLIANCE = True
MASK_COMPLIANCE_THRESHOLD = 150
HIGH_MASK_COMPLIANCE = 0.42
AUTO_MASK_RELAXATION = True
MASK_RELAXATION_THRESHOLD = 45

AUTO_TESTING_RATE = True
TESTING_RATE_THRESHOLD = 160
HIGH_TESTING_RATE = 0.38
AUTO_TESTING_RELAXATION = True
TESTING_RELAXATION_THRESHOLD = 45

AUTO_QUARANTINE_COMPLIANCE = True
QUARANTINE_COMPLIANCE_THRESHOLD = 160
HIGH_QUARANTINE_COMPLIANCE = 0.58
AUTO_QUARANTINE_RELAXATION = True
QUARANTINE_RELAXATION_THRESHOLD = 45

SENIOR_MOBILITY = 0.65
AUTO_SENIOR_MOBILITY_REDUCTION = True
SENIOR_MOBILITY_THRESHOLD = 130
LOW_SENIOR_MOBILITY = 0.40
AUTO_SENIOR_MOBILITY_RESTORE = True
SENIOR_MOBILITY_RESTORE_THRESHOLD = 40

CHILD_MOBILITY = 1.0
AUTO_CHILD_MOBILITY_REDUCTION = True
CHILD_MOBILITY_THRESHOLD = 110
LOW_CHILD_MOBILITY = 0.45
AUTO_CHILD_MOBILITY_RESTORE = True
CHILD_MOBILITY_RESTORE_THRESHOLD = 10

AUTO_VACCINATION_CAMPAIGN = False
VACCINATION_CAMPAIGN_THRESHOLD = 250
DAILY_VACCINATION_CAPACITY = 10

RANDOM_SEED = 42